/**
* Copyright @ 2019 - 2021 Nobo Automotive Technologies Co.,Ltd.
* All Rights Reserved.
*
* Redistribution and use in source and binary forms, with or without
* modification, are NOT permitted except as agreed by
* Nobo Automotive Technologies Co.,Ltd.
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*/

#ifndef __SWC_AL_CONFIG_H
#define	__SWC_AL_CONFIG_H

#include "Platform_Types.h"

#define	ALCM_DEBUG_EN		(0u)

#define ALCM_TASK				(5u)
#define ALCM_WAKEUPWAIT_TIME	(2000/ALCM_TASK)

#define	SWITCH_OFF		(0u)
#define	SWITCH_ON		(1u)

#define LINKAGE_FUNCTION_AEB			(0u)
#define LINKAGE_FUNCTION_FCW			(1u)
#define LINKAGE_FUNCTION_FCT			(2u)
#define LINKAGE_FUNCTION_LCA			(3u)
#define LINKAGE_FUNCTION_DOW			(4u)
#define LINKAGE_FUNCTION_DOOR			(5u)
#define LINKAGE_FUNCTION_TBD			(6u)
#define LINKAGE_FUNCTION_ACTEMP			(7u)
#define LINKAGE_FUNCTION_PM25			(8u)
#define	LINKAGE_FUNCTION_NUMBER			(9u)
#define	LINKAGE_FUNCTION_ID_INVALID		(0xFFu)


#define	LINKAGE_EVENT_AEB						(0u)
#define	LINKAGE_EVENT_FCW						(1u)
#define	LINKAGE_EVENT_FCT						(2u)
#define	LINKAGE_EVENT_LCA_LEFT					(3u)
#define	LINKAGE_EVENT_LCA_RIGHT					(4u)
#define	LINKAGE_EVENT_DOW_LEFT					(5u)
#define	LINKAGE_EVENT_DOW_RIGHT					(6u)
#define	LINKAGE_EVENT_DOOR_OPEN_DRIVE			(7u)
#define	LINKAGE_EVENT_DOOR_OPEN_PASSENGER		(8u)
#define	LINKAGE_EVENT_DOOR_OPEN_LR				(9u)
#define	LINKAGE_EVENT_DOOR_OPEN_RR				(10u)
#define	LINKAGE_EVENT_TBD_TURN_LEFT				(11u)
#define	LINKAGE_EVENT_TBD_TURN_RIGHT			(12u)
#define	LINKAGE_EVENT_DRVTEMP_UP				(13u)
#define	LINKAGE_EVENT_DRVTEMP_DOWN				(14u)
#define	LINKAGE_EVENT_PASSTTEMP_UP				(15u)
#define	LINKAGE_EVENT_PASSTTEMP_DOWN			(16u)
#define	LINKAGE_EVENT_PM25_POLLUTION_LOW		(17u)
#define	LINKAGE_EVENT_PM25_POLLUTION_MID		(18u)
#define	LINKAGE_EVENT_PM25_POLLUTION_HIGH		(19u)
#define	LINKAGE_EVENT_PM25_POLLUTION_SERIOUS	(20u)
#define	LINKAGE_EVENT_NUMBER					(21u)
#define	LINKAGE_EVENT_ID_INVALID				(0xFFu)

#if (LINKAGE_FUNCTION_NUMBER >= LINKAGE_FUNCTION_ID_INVALID)
	#error "LINKAGE_FUNCTION_NUMBER must litter than LINKAGE_FUNCTION_ID_INVALID"
#endif

#if (LINKAGE_EVENT_NUMBER >= LINKAGE_EVENT_ID_INVALID)
	#error "LINKAGE_EVENT_NUMBER must litter than LINKAGE_EVENT_ID_INVALID"
#endif

#define	LINKAGE_AREA_NUMBER					(7u)

#define	LINKAGE_SIGNAL_FREQ_NOACTION		(0x00u)
#define	LINKAGE_SIGNAL_FREQ_1HZ				(0x01u)
#define	LINKAGE_SIGNAL_FREQ_2HZ				(0x02u)
#define	LINKAGE_SIGNAL_FREQ_4HZ				(0x03u)
#define	LINKAGE_SIGNAL_FREQ_OFF				(0x04u)

#define	LINKAGE_SIGNAL_COLOR_NOACTION		(0x40u)
#define	LINKAGE_SIGNAL_COLOR_0X28			(0x28u)
#define	LINKAGE_SIGNAL_COLOR_0X38			(0x38u)
#define	LINKAGE_SIGNAL_COLOR_0X32			(0x32u)
#define	LINKAGE_SIGNAL_COLOR_0X3C			(0x3Cu)

#define	LINKAGE_SIGNAL_LIGHTLVL_NOACTION	(0x00u)
#define	LINKAGE_SIGNAL_LIGHTLVL_PECENT10	(0x01u)
#define	LINKAGE_SIGNAL_LIGHTLVL_PECENT20	(0x02u)
#define	LINKAGE_SIGNAL_LIGHTLVL_PECENT30	(0x03u)
#define	LINKAGE_SIGNAL_LIGHTLVL_PECENT40	(0x04u)
#define	LINKAGE_SIGNAL_LIGHTLVL_PECENT50	(0x05u)
#define	LINKAGE_SIGNAL_LIGHTLVL_PECENT60	(0x06u)
#define	LINKAGE_SIGNAL_LIGHTLVL_PECENT70	(0x07u)
#define	LINKAGE_SIGNAL_LIGHTLVL_PECENT80	(0x08u)
#define	LINKAGE_SIGNAL_LIGHTLVL_PECENT90	(0x09u)
#define	LINKAGE_SIGNAL_LIGHTLVL_PECENT100	(0x0Au)

#define	EVENT_IN_FUN_INDEX_0			(0u)
#define	EVENT_IN_FUN_INDEX_1			(1u)
#define	EVENT_IN_FUN_INDEX_2			(2u)
#define	EVENT_IN_FUN_INDEX_3			(3u)
#define	EVENT_IN_FUN_SLOT_NUMBER		(4u)

#define	EVENT_CLERA_BY_INPUTSIGNAL		(0x00u)
#define	EVENT_CLERA_BY_TIMEOUT			(0x01u)
#define	EVENT_CLERA_BY_INTERRUPT		(0x02u)
#define	EVENT_CLERA_BY_NOTEXECUTE		(0x04u)

#define	EVENT_CLERA_DEFAULT								(EVENT_CLERA_BY_INPUTSIGNAL)
#define	EVENT_CLERA_TIMEOUT_INTERRUPT_NOTEXECUTE		(EVENT_CLERA_BY_TIMEOUT | EVENT_CLERA_BY_INTERRUPT | EVENT_CLERA_BY_NOTEXECUTE)
#define	EVENT_CLERA_TIMEOUT_INTERRUPT					(EVENT_CLERA_BY_TIMEOUT | EVENT_CLERA_BY_INTERRUPT)

#define	EVENT_ATTRIBUT_NO_TIMEOUT		(0u)
#define	EVENT_ATTRIBUT_TIMEOUT_1S		(200u)
#define	EVENT_ATTRIBUT_TIMEOUT_3S		(600u)

#define	ALCM_POWER_MODE_NULL						(0x0000u)
#define	ALCM_POWER_MODE_OFF							(0x0001u)
#define	ALCM_POWER_MODE_RUN							(0x0002u)
#define	ALCM_POWER_MODE_ABNORMAL_VOLTAGE			(0x0004u)
#define	ALCM_POWER_MODE_SLEEP						(0x0008u)

#if 0
#define	EVENT_LIST_NUMBER_AEB		(1u)
#define	EVENT_LIST_NUMBER_FCW		(1u)
#define	EVENT_LIST_NUMBER_FCT		(1u)
#define	EVENT_LIST_NUMBER_LCA		(2u)
#define	EVENT_LIST_NUMBER_DOW		(2u)
#define	EVENT_LIST_NUMBER_DOOR		(4u)
#define	EVENT_LIST_NUMBER_TBD		(2u)
#define	EVENT_LIST_NUMBER_ACTEMP	(4u)
#define	EVENT_LIST_NUMBER_PM25		(4u)

#define	EVENT_LIST_AEB		{LINKAGE_EVENT_AEB}
#define	EVENT_LIST_FCW		{LINKAGE_EVENT_FCW}
#define	EVENT_LIST_FCT		{LINKAGE_EVENT_FCT}
#define	EVENT_LIST_LCA		{LINKAGE_EVENT_LCA_LEFT, LINKAGE_EVENT_LCA_RIGHT}
#define	EVENT_LIST_DOW		{LINKAGE_EVENT_DOW_LEFT, LINKAGE_EVENT_DOW_RIGHT}
#define	EVENT_LIST_DOOR		{LINKAGE_EVENT_DOOR_OPEN_DRIVE, LINKAGE_EVENT_DOOR_OPEN_PASSENGER, LINKAGE_EVENT_DOOR_OPEN_LR, LINKAGE_EVENT_DOOR_OPEN_RR}
#define	EVENT_LIST_TBD		{LINKAGE_EVENT_TBD_TURN_LEFT, LINKAGE_EVENT_TBD_TURN_RIGHT}
#define	EVENT_LIST_ACTEMP	{LINKAGE_EVENT_DRVTEMP_UP, LINKAGE_EVENT_DRVTEMP_DOWN, LINKAGE_EVENT_PASSTTEMP_UP, LINKAGE_EVENT_PASSTTEMP_DOWN}
#define	EVENT_LIST_PM25		{LINKAGE_EVENT_PM25_POLLUTION_LOW, LINKAGE_EVENT_PM25_POLLUTION_MID, LINKAGE_EVENT_PM25_POLLUTION_HIGH, LINKAGE_EVENT_PM25_POLLUTION_SERIOUS}
#endif

#define DEFINE_FUNC_ATTRIBUTE	\
{\
	{1,	/* 1,*/	AL_InputProcess_AEB,	AL_OutputValueGet_AEB},\
	{1,	/* 1,*/	AL_InputProcess_FCW,	AL_OutputValueGet_FCW},\
	{1,	/* 1,*/	AL_InputProcess_FCT,	AL_OutputValueGet_FCT},\
	{2,	/* 2,*/	AL_InputProcess_LCA,	AL_OutputValueGet_LCA},\
	{2,	/* 2,*/	AL_InputProcess_DOW,	AL_OutputValueGet_DOW},\
	{4,	/* 4,*/	AL_InputProcess_DOOR,	AL_OutputValueGet_DOOR},\
	{1,	/* 2,*/	AL_InputProcess_TBD,	AL_OutputValueGet_TBD},\
	{2,	/* 4,*/	AL_InputProcess_ACTEMP,	AL_OutputValueGet_ACTEMP},\
	{1,	/* 4,*/	AL_InputProcess_PM25,	AL_OutputValueGet_PM25},\
}

#define	DEFINE_EVENT_ATTRIBUTE	\
{\
	{\
		LINKAGE_FUNCTION_AEB, \
		EVENT_IN_FUN_INDEX_0, \
		/*1, */\
		EVENT_CLERA_DEFAULT, \
		EVENT_ATTRIBUT_NO_TIMEOUT,\
		LINKAGE_SIGNAL_FREQ_4HZ, \
		LINKAGE_SIGNAL_COLOR_0X38, \
		LINKAGE_SIGNAL_LIGHTLVL_PECENT50\
	},\
	\
	{\
		LINKAGE_FUNCTION_FCW, \
		EVENT_IN_FUN_INDEX_0, \
		/*1, */\
		EVENT_CLERA_DEFAULT, \
		EVENT_ATTRIBUT_NO_TIMEOUT,\
		LINKAGE_SIGNAL_FREQ_4HZ, \
		LINKAGE_SIGNAL_COLOR_0X38, \
		LINKAGE_SIGNAL_LIGHTLVL_PECENT50\
	},\
	\
	{\
		LINKAGE_FUNCTION_FCT, \
		EVENT_IN_FUN_INDEX_0, \
		/*1, */\
		EVENT_CLERA_DEFAULT, \
		EVENT_ATTRIBUT_NO_TIMEOUT,\
		LINKAGE_SIGNAL_FREQ_4HZ, \
		LINKAGE_SIGNAL_COLOR_0X38, \
		LINKAGE_SIGNAL_LIGHTLVL_PECENT50\
	},\
	\
	{\
		LINKAGE_FUNCTION_LCA, \
		EVENT_IN_FUN_INDEX_0, \
		/*1, */\
		EVENT_CLERA_DEFAULT, \
		EVENT_ATTRIBUT_NO_TIMEOUT,\
		LINKAGE_SIGNAL_FREQ_4HZ, \
		LINKAGE_SIGNAL_COLOR_0X38, \
		LINKAGE_SIGNAL_LIGHTLVL_PECENT50\
	},\
	\
	{\
		LINKAGE_FUNCTION_LCA, \
		EVENT_IN_FUN_INDEX_1, \
		/*1, */\
		EVENT_CLERA_DEFAULT, \
		EVENT_ATTRIBUT_NO_TIMEOUT,\
		LINKAGE_SIGNAL_FREQ_4HZ, \
		LINKAGE_SIGNAL_COLOR_0X38, \
		LINKAGE_SIGNAL_LIGHTLVL_PECENT50\
	},\
	\
	{\
		LINKAGE_FUNCTION_DOW, \
		EVENT_IN_FUN_INDEX_0, \
		/*1, */\
		EVENT_CLERA_DEFAULT, \
		EVENT_ATTRIBUT_NO_TIMEOUT,\
		LINKAGE_SIGNAL_FREQ_4HZ, \
		LINKAGE_SIGNAL_COLOR_0X38, \
		LINKAGE_SIGNAL_LIGHTLVL_PECENT50\
	},\
	\
	{\
		LINKAGE_FUNCTION_DOW, \
		EVENT_IN_FUN_INDEX_1, \
		/*1, */\
		EVENT_CLERA_DEFAULT, \
		EVENT_ATTRIBUT_NO_TIMEOUT,\
		LINKAGE_SIGNAL_FREQ_4HZ, \
		LINKAGE_SIGNAL_COLOR_0X38, \
		LINKAGE_SIGNAL_LIGHTLVL_PECENT50\
	},\
	\
	{\
		LINKAGE_FUNCTION_DOOR, \
		EVENT_IN_FUN_INDEX_0, \
		/*1, */\
		EVENT_CLERA_DEFAULT, \
		EVENT_ATTRIBUT_NO_TIMEOUT,\
		LINKAGE_SIGNAL_FREQ_2HZ, \
		LINKAGE_SIGNAL_COLOR_0X38, \
		LINKAGE_SIGNAL_LIGHTLVL_PECENT50\
	},\
	\
	{\
		LINKAGE_FUNCTION_DOOR, \
		EVENT_IN_FUN_INDEX_1, \
		/*1, */\
		EVENT_CLERA_DEFAULT, \
		EVENT_ATTRIBUT_NO_TIMEOUT,\
		LINKAGE_SIGNAL_FREQ_2HZ, \
		LINKAGE_SIGNAL_COLOR_0X38, \
		LINKAGE_SIGNAL_LIGHTLVL_PECENT50\
	},\
	\
	{\
		LINKAGE_FUNCTION_DOOR, \
		EVENT_IN_FUN_INDEX_2, \
		/*1, */\
		EVENT_CLERA_DEFAULT, \
		EVENT_ATTRIBUT_NO_TIMEOUT,\
		LINKAGE_SIGNAL_FREQ_2HZ, \
		LINKAGE_SIGNAL_COLOR_0X38, \
		LINKAGE_SIGNAL_LIGHTLVL_PECENT50\
	},\
	\
	{\
		LINKAGE_FUNCTION_DOOR, \
		EVENT_IN_FUN_INDEX_3, \
		/*1, */\
		EVENT_CLERA_DEFAULT, \
		EVENT_ATTRIBUT_NO_TIMEOUT,\
		LINKAGE_SIGNAL_FREQ_2HZ, \
		LINKAGE_SIGNAL_COLOR_0X38, \
		LINKAGE_SIGNAL_LIGHTLVL_PECENT50\
	},\
	\
	{\
		LINKAGE_FUNCTION_TBD, \
		EVENT_IN_FUN_INDEX_0, \
		/*1, */\
		EVENT_CLERA_DEFAULT, \
		EVENT_ATTRIBUT_NO_TIMEOUT,\
		LINKAGE_SIGNAL_FREQ_1HZ, \
		LINKAGE_SIGNAL_COLOR_0X38, \
		LINKAGE_SIGNAL_LIGHTLVL_PECENT50\
	},\
	\
	{\
		LINKAGE_FUNCTION_TBD, \
		EVENT_IN_FUN_INDEX_0, \
		/*2, */\
		EVENT_CLERA_DEFAULT, \
		EVENT_ATTRIBUT_NO_TIMEOUT,\
		LINKAGE_SIGNAL_FREQ_1HZ, \
		LINKAGE_SIGNAL_COLOR_0X38, \
		LINKAGE_SIGNAL_LIGHTLVL_PECENT50\
	},\
	\
	{\
		LINKAGE_FUNCTION_ACTEMP, \
		EVENT_IN_FUN_INDEX_0, \
		/*1, */\
		EVENT_CLERA_TIMEOUT_INTERRUPT_NOTEXECUTE, \
		EVENT_ATTRIBUT_TIMEOUT_1S,\
		LINKAGE_SIGNAL_FREQ_1HZ, \
		LINKAGE_SIGNAL_COLOR_0X38, \
		LINKAGE_SIGNAL_LIGHTLVL_PECENT50\
	},\
	\
	{\
		LINKAGE_FUNCTION_ACTEMP, \
		EVENT_IN_FUN_INDEX_0, \
		/*2, */\
		EVENT_CLERA_TIMEOUT_INTERRUPT_NOTEXECUTE, \
		EVENT_ATTRIBUT_TIMEOUT_1S,\
		LINKAGE_SIGNAL_FREQ_1HZ, \
		LINKAGE_SIGNAL_COLOR_0X28, \
		LINKAGE_SIGNAL_LIGHTLVL_PECENT50\
	},\
	\
	{\
		LINKAGE_FUNCTION_ACTEMP, \
		EVENT_IN_FUN_INDEX_1, \
		/*1, */\
		EVENT_CLERA_TIMEOUT_INTERRUPT_NOTEXECUTE, \
		EVENT_ATTRIBUT_TIMEOUT_1S,\
		LINKAGE_SIGNAL_FREQ_1HZ, \
		LINKAGE_SIGNAL_COLOR_0X38, \
		LINKAGE_SIGNAL_LIGHTLVL_PECENT50\
	},\
	\
	{\
		LINKAGE_FUNCTION_ACTEMP, \
		EVENT_IN_FUN_INDEX_1, \
		/*2, */\
		EVENT_CLERA_TIMEOUT_INTERRUPT_NOTEXECUTE, \
		EVENT_ATTRIBUT_TIMEOUT_1S,\
		LINKAGE_SIGNAL_FREQ_1HZ, \
		LINKAGE_SIGNAL_COLOR_0X28, \
		LINKAGE_SIGNAL_LIGHTLVL_PECENT50\
	},\
	\
	{\
		LINKAGE_FUNCTION_PM25, \
		EVENT_IN_FUN_INDEX_0, \
		/*1, */\
		EVENT_CLERA_TIMEOUT_INTERRUPT, \
		EVENT_ATTRIBUT_TIMEOUT_3S,\
		LINKAGE_SIGNAL_FREQ_2HZ, \
		LINKAGE_SIGNAL_COLOR_0X32, \
		LINKAGE_SIGNAL_LIGHTLVL_PECENT50\
	},\
	\
	{\
		LINKAGE_FUNCTION_PM25, \
		EVENT_IN_FUN_INDEX_0, \
		/*2, */\
		EVENT_CLERA_TIMEOUT_INTERRUPT, \
		EVENT_ATTRIBUT_TIMEOUT_3S,\
		LINKAGE_SIGNAL_FREQ_2HZ, \
		LINKAGE_SIGNAL_COLOR_0X3C, \
		LINKAGE_SIGNAL_LIGHTLVL_PECENT50\
	},\
	\
	{\
		LINKAGE_FUNCTION_PM25, \
		EVENT_IN_FUN_INDEX_0, \
		/*3, */\
		EVENT_CLERA_TIMEOUT_INTERRUPT, \
		EVENT_ATTRIBUT_TIMEOUT_3S,\
		LINKAGE_SIGNAL_FREQ_2HZ, \
		LINKAGE_SIGNAL_COLOR_0X38, \
		LINKAGE_SIGNAL_LIGHTLVL_PECENT50\
	},\
	\
	{\
		LINKAGE_FUNCTION_PM25, \
		EVENT_IN_FUN_INDEX_0, \
		/*4, */\
		EVENT_CLERA_DEFAULT, \
		EVENT_ATTRIBUT_NO_TIMEOUT,\
		LINKAGE_SIGNAL_FREQ_2HZ, \
		LINKAGE_SIGNAL_COLOR_0X38, \
		LINKAGE_SIGNAL_LIGHTLVL_PECENT50\
	},\
}

#endif

